#!/bin/bash

LOG_FILE="griveSyncLog-CB.log"
SERVICE="grive^"

if ps ax | grep -v grep | grep $SERVICE > /dev/null; then 
   #echo "$SERVICE running, everything is fine"
   notify-send Grive "Grive already running";
else 
   #echo "$SERVICE is not running"
   if ping -q -c 1 -W 1 google.com >/dev/null; then
      #echo "The network is up"
      notify-send Grive "Starting Sync";

      grive -l $LOG_FILE

      while read -r line; do
         if [ "$line" = "Finished!" ]; then
            notify-send Grive "Sync Complete";
         fi
      done < $LOG_FILE

   else
      #echo "The network is down"
      notify-send Grive "No Network. Aborting Sync";
      exit
   fi 
fi

#if ping -q -c 1 -W 1 google.com >/dev/null; then
#   #echo "The network is up"
#   notify-send Grive "Starting Sync";
#
#   grive -l $LOG_FILE
#
#   while read -r line; do
#      if [ "$line" = "Finished!" ]; then
#         notify-send Grive "Sync Complete";
#      fi
#   done < $LOG_FILE
#
#else
#   #echo "The network is down"
#   notify-send Grive "No Network. Aborting Sync";
#   exit
#fi
#
#grive -l $LOG_FILE

#while read -r line; do 
#   if [ "$line" = "Finished!" ]; then
#      notify-send Grive "Sync Complete";
#   fi
#   done < $LOG_FILE 
