#!/bin/bash

#LOG_FILE="griveSyncLog-CB.log"
SERVICE="grive"

function show_usage {
   echo "Usage: $0 griveSyncLogName.log"
   exit 1
}


if [ $# -ne 1 ]; then
   show_usage
else # There are two arguments
   LOG_FILE=$1
fi

if ps ax | grep -v grep | grep -w $SERVICE > /dev/null; then 
   #echo "$SERVICE running, everything is fine"
   notify-send Grive "Grive already running";
else 
   #echo "$SERVICE is not running"
   if ping -q -c 1 -W 1 google.com >/dev/null; then
      #echo "The network is up"a

      if [[ -e $LOG_FILE ]]; then
         mv $LOG_FILE $LOG_FILE-1
      fi
      
      notify-send Grive "Starting Sync";

      grive -l $LOG_FILE

      while read -r line; do
         if [ "$line" = "Finished!" ]; then
            notify-send Grive "Sync Complete";
            sleep 5
            RMV_COUNT=diff -u $LOG_FILE  $LOG_FILE-1 | grep -v $LOG_FILE | grep -v ^@ | grep ^- | wc -l
            ADD_COUNT=diff -u $LOG_FILE  $LOG_FILE-1 | grep -v $LOG_FILE | grep -v ^@ | grep ^+ | wc -l
            notify-send Grive "$RMV_COUNT files removed, $ADD_COUNT added";
         fi
      done < $LOG_FILE

   else
      #echo "The network is down"
      notify-send Grive "No Network. Aborting Sync";
      exit
   fi 
fi
